# nginx-deployment-service.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3 # You can adjust the number of desired replicas here
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest # Using the latest Nginx image
        ports:
        - containerPort: 80 # Nginx default HTTP port

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx # This selector matches the labels of the pods created by the deployment
  ports:
    - protocol: TCP
      port: 80 # The port the service will expose
      targetPort: 80 # The port on the pod that the service will send traffic to
  type: LoadBalancer # Use LoadBalancer for external access, or ClusterIP for internal only
